const {test, expect} = require('@playwright/test');
const baseUrl=(process.env.NEXA_LIVE_URL||'').replace(/\/$/,'');
const email=process.env.NEXA_LIVE_EMAIL||process.env.NEXA_LIVE_USERNAME||'';
const password=process.env.NEXA_LIVE_PASSWORD||'';

test('Landing page templates and builder remain responsive',async({page})=>{
    test.setTimeout(60_000);
    test.skip(!baseUrl||!email||!password,'Live Nexa credentials were not provided.');
    const errors=[]; page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`${baseUrl}/login/`);
    await page.locator('#field-userName').fill(email);
    await page.locator('#field-password').fill(password);
    await page.locator('#login-form button[type="submit"]').click();
    await page.waitForURL(/\/w\/[^/]+(?:\/.*)?$/,{timeout:30_000});
    const workspace=page.url().match(/^(.*\/w\/[^/]+)/)?.[1];
    await page.goto(`${workspace}/NexaLandingPages`);
    await expect(page.getByRole('heading',{name:'Landing Pages'})).toBeVisible();
    await expect(page.locator('[data-workspace-table="landing-pages"]')).toBeVisible();
    await page.getByRole('button',{name:'New landing page'}).click();
    await expect(page.getByRole('heading',{name:'Choose a landing page design'})).toBeVisible();
    await expect(page.locator('.nexa-template-card')).toHaveCount(4);
    await page.locator('[data-action="preview-template"]').first().click();
    const dialog=page.getByRole('dialog',{name:'Page preview'});
    await expect(dialog).toBeVisible();
    await dialog.getByRole('button',{name:'Close'}).click();
    await page.locator('[data-action="use-template"]').first().click();
    await expect(page.getByRole('heading',{name:'New landing page'})).toBeVisible();
    await expect(page.locator('.nexa-preview-block')).toHaveCount(6);
    await expect(page.locator('.nexa-preview-photo img')).toBeVisible();
    const canvasHeading=page.locator('.nexa-preview-block.is-hero [data-inline-field="heading"]');
    await canvasHeading.fill('A tailored demo for modern teams');
    await canvasHeading.press('Tab');
    await expect(page.locator('[data-block-settings] [name="heading"]')).toHaveValue('A tailored demo for modern teams');
    const formSelect=page.locator('[data-block-settings] [name="formId"]');
    await page.locator('.nexa-preview-block.is-form').click();
    if(await formSelect.locator('option').count()>1)await formSelect.selectOption({index:1});
    await page.locator('[data-page-settings] [name="name"]').fill('Browser preview page');
    await expect(page.locator('[data-page-settings] [name="slug"]')).toHaveValue('browser-preview-page');
    await page.getByRole('button',{name:'Preview'}).click();
    await expect(dialog).toBeVisible();
    const previewFrame=dialog.locator('[data-preview-frame]');
    await expect(previewFrame.contentFrame().locator('a[href="#demo-form"]')).toHaveCount(2);
    if(await formSelect.locator('option').count()>1)await expect(previewFrame.contentFrame().locator('iframe[src*="LeadCaptureForm"]')).toBeVisible();
    const box=await dialog.boundingBox(); const viewport=page.viewportSize();
    expect(Math.abs(box.x+box.width/2-viewport.width/2)).toBeLessThan(4);
    await dialog.getByRole('button',{name:'Close'}).click();
    expect(errors).toEqual([]);
});
