define('custom:views/landing-page/workspace', ['view', 'custom:workspace-table'], (Dep, WorkspaceTable) => class extends Dep {
    template = 'custom:landing-page/workspace';
    events = {
        'click [data-action="reload"]': 'load', 'click [data-action="new-page"]': 'newPage', 'click [data-action="back-to-pages"]': 'backToPages',
        'click [data-action="close-templates"]': 'closeTemplates', 'click [data-action="start-blank"]': 'startBlank',
        'click [data-action="use-template"]': 'useTemplate', 'click [data-action="preview-template"]': 'previewTemplate',
        'click [data-action="save-page"]': 'savePage', 'click [data-action="publish-page"]': 'publishPage', 'click [data-action="preview-page"]': 'previewDraft',
        'click [data-action="close-preview"]': 'closePreview', 'click [data-action="edit-page"]': 'editPage', 'click [data-action="open-page"]': 'openPage',
        'click [data-action="archive-page"]': 'askArchive', 'click [data-action="close-archive"]': 'closeArchive', 'click [data-action="confirm-archive"]': 'confirmArchive',
        'click [data-add-block]': 'addBlock', 'click [data-select-block]': 'selectBlock', 'click [data-block-action]': 'blockAction', 'click [data-settings-tab]': 'settingsTab',
        'click [data-action="change-block-image"]': 'chooseBlockImage', 'change [data-landing-image-upload]': 'uploadBlockImage',
        'blur [data-inline-field]': 'inlineEdit', 'keydown [data-inline-field]': 'inlineKeydown',
        'input [data-page-settings]': 'pageSettingsChanged', 'input [data-block-settings]': 'blockSettingsChanged', 'change [data-block-settings]': 'blockSettingsChanged',
        'input [data-page-search]': 'renderRows', 'change [data-page-status]': 'renderRows', 'click [data-page-sort]': 'sortPages',
    };

    setup() { this.setPageTitle('Landing Pages'); this.pages = []; this.forms = []; this.assets = []; this.templates = []; this.assetPreviewUrls = new Map(); this.current = null; this.selectedBlockId = null; this.orderBy = 'modifiedAt'; this.direction = 'desc'; this.tableManager = new WorkspaceTable(this); }
    afterRender() { super.afterRender(); this.element.querySelectorAll('.nexa-landing-modal').forEach(node => this.dialog(node, false)); this.load(); }

    async load() {
        this.state('loading');
        try { const data = await Espo.Ajax.getRequest('Nexa/landing-pages/workspace'); this.pages = data.pages || []; this.forms = data.forms || []; this.assets = data.assets || []; this.templates = data.templates || []; this.populateChoices(); this.renderTemplates(); this.renderRows(); this.state('ready'); }
        catch (error) { this.state('error'); Espo.Ui.error(error?.message || 'Landing pages could not be loaded.'); }
    }
    state(value) { this.element.querySelectorAll('[data-landing-state]').forEach(node => { node.hidden = node.dataset.landingState !== value; node.style.display = node.hidden ? 'none' : ''; }); }
    populateChoices() { this.element.querySelector('[data-page-assets]').innerHTML = '<option value="">Choose an asset</option>' + this.assets.map(item => `<option value="${this.escape(item.id)}">${this.escape(item.display_name)}</option>`).join(''); this.element.querySelector('[data-page-forms]').innerHTML = '<option value="">Choose a form</option>' + this.forms.map(item => `<option value="${this.escape(item.id)}">${this.escape(item.name)}</option>`).join(''); }

    renderRows() {
        const query = (this.element.querySelector('[data-page-search]')?.value || '').trim().toLowerCase(); const status = this.element.querySelector('[data-page-status]')?.value || 'all';
        const list = this.pages.filter(page => (!query || `${page.name} ${page.slug} ${page.locale}`.toLowerCase().includes(query)) && (status === 'all' || page.status === status)).sort((a, b) => { const av = a[this.orderBy] ?? ''; const bv = b[this.orderBy] ?? ''; return String(av).localeCompare(String(bv), undefined, {numeric: true}) * (this.direction === 'asc' ? 1 : -1); });
        this.element.querySelector('[data-page-rows]').innerHTML = list.map(page => `<tr><td data-column="name"><span class="nexa-page-name"><span class="fas fa-window-maximize"></span><span><strong>${this.escape(page.name)}</strong><small>/${this.escape(page.slug)}</small></span></span></td><td data-column="status"><span class="nexa-page-badge is-${this.escape(page.status)}">${this.escape(page.status)}</span>${page.hasUnpublishedChanges && page.status === 'published' ? '<small>Draft changes</small>' : ''}</td><td data-column="locale">${this.escape(page.locale)}</td><td data-column="views">${Number(page.views || 0)}</td><td data-column="clicks">${Number(page.clicks || 0)}</td><td data-column="modifiedAt">${this.date(page.modifiedAt)}</td><td data-column="actions"><div class="nexa-page-actions"><button class="btn btn-icon" data-action="edit-page" data-id="${this.escape(page.id)}" title="Edit"><span class="fas fa-pen"></span></button>${page.url ? `<button class="btn btn-icon" data-action="open-page" data-id="${this.escape(page.id)}" title="Open published page"><span class="fas fa-external-link-alt"></span></button>` : ''}${page.status !== 'archived' ? `<button class="btn btn-icon" data-action="archive-page" data-id="${this.escape(page.id)}" title="Archive"><span class="fas fa-archive"></span></button>` : ''}</div></td></tr>`).join('') || '<tr><td colspan="7" class="text-center"><strong>No landing pages found</strong><br><span>Create a page or adjust the filters.</span></td></tr>';
        this.element.querySelector('[data-page-total]').textContent = `${list.length} ${list.length === 1 ? 'page' : 'pages'}`; this.tableManager.enhance(this.element.querySelector('[data-workspace-table="landing-pages"]'), 'landing-pages');
    }
    sortPages(event) { const key = event.currentTarget.dataset.pageSort; this.direction = this.orderBy === key && this.direction === 'asc' ? 'desc' : 'asc'; this.orderBy = key; this.renderRows(); }

    newPage() { this.element.querySelector('[data-landing-list]').hidden = true; this.element.querySelector('[data-landing-editor]').hidden = true; this.element.querySelector('[data-template-gallery]').hidden = false; this.renderTemplates(); }
    closeTemplates() { this.element.querySelector('[data-template-gallery]').hidden = true; this.element.querySelector('[data-landing-list]').hidden = false; }
    startBlank() { const hero = this.makeBlock('hero'); this.openEditor({id: null, name: '', slug: '', locale: 'en', seoTitle: '', seoDescription: '', canonicalUrl: '', noIndex: false, primaryColor: '#087d71', backgroundColor: '#ffffff', textColor: '#172f35', blocks: [hero]}); }
    renderTemplates() { const grid=this.element.querySelector('[data-template-grid]'); if(!grid)return; grid.innerHTML=this.templates.map(template=>`<article class="nexa-template-card"><div class="nexa-template-photo"><img src="${this.escape(template.thumbnail)}" alt=""><span>${this.escape(template.category)}</span></div><div class="nexa-template-copy"><h2>${this.escape(template.name)}</h2><p>${this.escape(template.description)}</p><div><button class="btn btn-default" type="button" data-action="preview-template" data-template-id="${this.escape(template.id)}"><span class="fas fa-eye"></span> Preview</button><button class="btn btn-primary" type="button" data-action="use-template" data-template-id="${this.escape(template.id)}">Use template</button></div></div></article>`).join(''); const notice=this.element.querySelector('[data-template-form-notice]'); notice.hidden=this.forms.length>0; }
    useTemplate(event) { const template=this.templates.find(item=>item.id===event.currentTarget.dataset.templateId); if(!template)return; const page=JSON.parse(JSON.stringify(template.configuration)); page.name=`${page.name} - Draft`; page.slug=this.slug(page.name); this.openEditor({...page,id:null}); }
    previewTemplate(event) { const template=this.templates.find(item=>item.id===event.currentTarget.dataset.templateId); if(!template)return; const previous=this.current; this.current=JSON.parse(JSON.stringify(template.configuration)); this.bindAvailableForms(); const dialog=this.element.querySelector('[data-preview-dialog]'); dialog.querySelector('[data-preview-frame]').srcdoc=this.previewDocument(); dialog.dataset.templatePreview='1'; this.dialog(dialog,true); this.current=previous; }
    editPage(event) { const page = this.pages.find(item => item.id === event.currentTarget.dataset.id); if (page) this.openEditor({...page.configuration, id: page.id, status: page.status}); }
    openEditor(page) { this.current = JSON.parse(JSON.stringify(page)); this.current.blocks ||= []; this.repairAnchors(); this.bindAvailableForms(); this.selectedBlockId = this.current.blocks[0]?.id || null; this.element.querySelector('[data-landing-list]').hidden = true; this.element.querySelector('[data-template-gallery]').hidden = true; this.element.querySelector('[data-landing-editor]').hidden = false; this.fillPageSettings(); this.renderCanvas(); if (this.selectedBlockId) this.fillBlockSettings(this.selectedBlockId); this.settingsTab({currentTarget: this.element.querySelector('[data-settings-tab="page"]')}); this.element.querySelector('[data-builder-title]').textContent = this.current.id ? this.current.name : 'New landing page'; this.error(''); const ids=[...new Set(this.current.blocks.map(block=>block.assetId).filter(Boolean))]; Promise.all(ids.map(id=>this.ensureAssetPreview(id))).then(()=>this.current&&this.renderCanvas()); }
    repairAnchors() { const ids=new Set(this.current.blocks.map(block=>block.id)); this.current.blocks.forEach(block=>{if(!String(block.buttonUrl||'').startsWith('#'))return;const target=block.buttonUrl.slice(1);if(ids.has(target))return;const match=this.current.blocks.find(candidate=>candidate.id.startsWith(`${target}-`));if(match)block.buttonUrl=`#${match.id}`;}); }
    bindAvailableForms() { const blocks=this.current?.blocks||[]; const referenced=this.forms.find(form=>blocks.some(block=>this.formPublicId(block.buttonUrl)===form.publicId)); const fallback=this.forms.length===1?this.forms[0]:null; blocks.filter(block=>block.type==='form'&&!block.formId).forEach(block=>{block.formId=(referenced||fallback)?.id||null;}); }
    formPublicId(value) { const match=String(value||'').match(/[?&]id=([^&#]+)/); if(!match)return null; try{return decodeURIComponent(match[1]);}catch{return match[1];} }
    backToPages() { this.element.querySelector('[data-landing-editor]').hidden = true; this.element.querySelector('[data-template-gallery]').hidden = true; this.element.querySelector('[data-landing-list]').hidden = false; this.current = null; this.selectedBlockId = null; }

    fillPageSettings() { const form = this.element.querySelector('[data-page-settings]'); ['name','slug','locale','seoTitle','seoDescription','canonicalUrl','primaryColor','backgroundColor','textColor'].forEach(name => form.elements[name].value = this.current[name] || ''); form.elements.noIndex.checked = !!this.current.noIndex; }
    pageSettingsChanged(event) { const form = event.currentTarget; const name = event.target.name; if (!name) return; if (name === 'noIndex') this.current[name] = event.target.checked; else this.current[name] = event.target.value; if (name === 'name' && !this.current.id && !form.elements.slug.dataset.touched) { this.current.slug = this.slug(event.target.value); form.elements.slug.value = this.current.slug; } if (name === 'slug') { form.elements.slug.dataset.touched = '1'; this.current.slug = this.slug(event.target.value); } if (name === 'name') this.element.querySelector('[data-builder-title]').textContent = event.target.value || 'New landing page'; this.renderCanvas(); }

    addBlock(event) { const block = this.makeBlock(event.currentTarget.dataset.addBlock); this.current.blocks.push(block); this.selectedBlockId = block.id; this.renderCanvas(); this.selectBlock(block.id); }
    makeBlock(type) { const defaults = {hero:{heading:'A clear promise for your audience',text:'Explain the value and give visitors one focused next step.',buttonLabel:'Get started',buttonUrl:'/contact'},features:{heading:'Why this matters',text:'Introduce the benefits that matter most.',items:[{title:'First benefit',text:'Explain the practical value.'},{title:'Second benefit',text:'Make the outcome specific.'},{title:'Third benefit',text:'Give visitors a reason to act.'}]},stats:{heading:'Proof at a glance',text:'Use credible figures that reinforce the story.',items:[{title:'25%',text:'Example outcome'},{title:'3x',text:'Example improvement'},{title:'24/7',text:'Example availability'}]},testimonial:{heading:'A concise, credible customer quote belongs here.',text:'Add one sentence of context.',items:[{title:'Customer name',text:'Role',meta:'Company'}]},text:{heading:'Tell the story',text:'Add the context visitors need to make a confident decision.'},image:{heading:'',text:''},form:{heading:'Start the conversation',text:'Complete the form and the team will follow up.',formMode:'modal',formButtonLabel:'Open form'},cta:{heading:'Ready for the next step?',text:'Make the action clear and specific.',buttonLabel:'Contact us',buttonUrl:'/contact'},divider:{}}; return {id:`block-${Date.now()}-${Math.random().toString(16).slice(2,8)}`,type,buttonNewTab:false,...(defaults[type] || {})}; }
    selectBlock(input) { const id = typeof input === 'string' ? input : input.currentTarget.dataset.selectBlock; const inline=typeof input!=='string'&&!!input.target.closest('[data-inline-field]'); this.selectedBlockId = id; this.settingsTab({currentTarget: this.element.querySelector('[data-settings-tab="block"]')}); if(!inline)this.renderCanvas(); this.fillBlockSettings(id); }
    fillBlockSettings(id) { const block = this.current.blocks.find(item => item.id === id); const form = this.element.querySelector('[data-block-settings]'); if (!block) return; form.querySelector('[data-selected-type]').textContent = this.title(block.type) + ' block'; ['eyebrow','heading','text','assetId','altText','caption','formId','formMode','formButtonLabel','buttonLabel','buttonUrl'].forEach(name => { if (!form.elements[name]) return; const fallback=name==='formMode'?'modal':name==='formButtonLabel'&&block.type==='form'?'Open form':''; form.elements[name].value=block[name]||fallback; }); form.elements.buttonNewTab.checked=!!block.buttonNewTab; form.elements.itemsText.value=(block.items||[]).map(item=>[item.title,item.text,item.meta].filter(value=>value).join(' | ')).join('\n'); const fields = {hero:['eyebrow','heading','text','assetId','altText','buttonLabel','buttonUrl','buttonNewTab'],features:['eyebrow','heading','text','itemsText'],stats:['heading','text','itemsText'],testimonial:['heading','text','itemsText'],text:['heading','text'],image:['assetId','altText','caption'],form:['heading','text','formId','formMode','formButtonLabel'],cta:['heading','text','buttonLabel','buttonUrl','buttonNewTab'],divider:[]}; form.querySelectorAll('[data-block-field]').forEach(node => node.hidden = !(fields[block.type] || []).includes(node.dataset.blockField)); }
    async blockSettingsChanged(event) { const block = this.current.blocks.find(item => item.id === this.selectedBlockId); if (!block || !event.target.name) return; if(event.target.name==='itemsText') block.items=event.target.value.split(/\r?\n/).filter(Boolean).slice(0,8).map(line=>{const [title='',text='',meta='']=line.split('|').map(value=>value.trim());return {title,text,meta};}); else block[event.target.name] = event.target.type==='checkbox'?event.target.checked:event.target.value; if(event.target.name==='assetId'&&event.target.value){block.templateImage=null;await this.ensureAssetPreview(event.target.value);} this.renderCanvas(); }
    blockAction(event) { event.stopPropagation(); const id = event.currentTarget.dataset.id; const index = this.current.blocks.findIndex(item => item.id === id); if (index < 0) return; const action = event.currentTarget.dataset.blockAction; if (action === 'delete') { this.current.blocks.splice(index,1); this.selectedBlockId = this.current.blocks[Math.min(index,this.current.blocks.length-1)]?.id || null; } if (action === 'up' && index > 0) [this.current.blocks[index-1],this.current.blocks[index]]=[this.current.blocks[index],this.current.blocks[index-1]]; if (action === 'down' && index < this.current.blocks.length-1) [this.current.blocks[index+1],this.current.blocks[index]]=[this.current.blocks[index],this.current.blocks[index+1]]; this.renderCanvas(); if (this.selectedBlockId) this.selectBlock(this.selectedBlockId); }

    renderCanvas() { if (!this.current) return; const canvas = this.element.querySelector('[data-builder-canvas]'); const style = `--page-primary:${this.current.primaryColor || '#087d71'};--page-background:${this.current.backgroundColor || '#fff'};--page-text:${this.current.textColor || '#172f35'}`; canvas.innerHTML = `<div class="nexa-canvas-page" style="${style}">${this.current.blocks.length ? this.current.blocks.map(block => this.blockPreview(block)).join('') : '<div class="nexa-canvas-empty"><span>Add a content block to begin.</span></div>'}</div>`; }
    blockPreview(block, interactive=true) {
        const controls=interactive?`<span class="nexa-block-controls"><button data-block-action="up" data-id="${this.escape(block.id)}" title="Move up"><span class="fas fa-arrow-up"></span></button><button data-block-action="down" data-id="${this.escape(block.id)}" title="Move down"><span class="fas fa-arrow-down"></span></button><button data-block-action="delete" data-id="${this.escape(block.id)}" title="Remove"><span class="fas fa-trash"></span></button></span>`:'';
        const heading=this.editable(block,'heading',block.heading||'',block.type==='hero'?'h1':'h2',interactive,true); const text=this.editable(block,'text',block.text||'','p',interactive,false); const eyebrow=block.eyebrow?this.editable(block,'eyebrow',block.eyebrow,'small',interactive,true):'';
        const asset=this.assets.find(item=>item.id===block.assetId); const form=this.forms.find(item=>item.id===block.formId); const imageUrl=block.templateImage?this.templateImageUrl(block.templateImage):null;
        const assetUrl=block.assetId?this.assetPreviewUrls.get(block.assetId):null; const resolvedImage=assetUrl||imageUrl;
        const image=resolvedImage?`<div class="nexa-preview-photo"><img src="${this.escape(resolvedImage)}" alt="${this.escape(block.altText||asset?.alt_text||'')}">${interactive?'<button type="button" class="nexa-change-image" data-action="change-block-image"><span class="fas fa-image"></span> Change image</button>':''}</div>`:interactive?`<button type="button" class="nexa-preview-image" data-action="change-block-image"><span class="fas fa-upload"></span> Upload an image</button>`:'';
        const items=(block.items||[]).map((item,index)=>`<article>${this.editable(block,'title',item.title||'','strong',interactive,true,index)}${this.editable(block,'text',item.text||'','p',interactive,false,index)}${item.meta?this.editable(block,'meta',item.meta,'small',interactive,true,index):''}</article>`).join('');
        let content='';
        if(block.type==='hero')content=`<div class="nexa-preview-copy">${eyebrow}${heading}${text}${this.previewButton(block,interactive)}</div>${image}`;
        if(block.type==='text')content=`${heading}${text}`;
        if(block.type==='image')content=`${image}${block.caption?this.editable(block,'caption',block.caption,'p',interactive,false):''}`;
        if(block.type==='form')content=`<div>${heading}${text}</div>${this.formPreview(block,form,interactive)}`;
        if(block.type==='cta')content=`<div>${heading}${text}</div>${this.previewButton(block,interactive)}`;
        if(block.type==='features')content=`<div class="nexa-preview-section-heading">${eyebrow}${heading}${text}</div><div class="nexa-preview-items">${items}</div>`;
        if(block.type==='stats')content=`<div class="nexa-preview-section-heading">${heading}${text}</div><div class="nexa-preview-items is-stats">${items}</div>`;
        if(block.type==='testimonial')content=`<blockquote>&ldquo;${this.editable(block,'heading',block.heading||'','span',interactive,false)}</blockquote>${text}<div class="nexa-preview-person">${items}</div>`;
        if(block.type==='divider')content='<hr>';
        return `<section class="nexa-preview-block is-${this.escape(block.type)} ${block.id===this.selectedBlockId&&interactive?'is-selected':''}"${interactive?` data-select-block="${this.escape(block.id)}"`:''}>${controls}${content}</section>`;
    }
    editable(block,field,value,tag,interactive,singleLine,itemIndex=null) { if(!interactive)return `<${tag}>${this.escape(value)}</${tag}>`; const item=itemIndex===null?'':` data-inline-item-index="${itemIndex}"`; return `<${tag} contenteditable="true" spellcheck="true" data-inline-field="${field}" data-block-id="${this.escape(block.id)}"${item}${singleLine?' data-single-line="1"':''}>${this.escape(value)}</${tag}>`; }
    previewButton(block,interactive) { const label=block.buttonLabel||'Call to action'; if(interactive)return `<span class="nexa-preview-button" contenteditable="true" data-inline-field="buttonLabel" data-block-id="${this.escape(block.id)}" data-single-line="1">${this.escape(label)}</span>`; let href=block.buttonUrl||'#'; let modal=''; const targetBlock=this.linkedFormBlock(href); const form=targetBlock?this.forms.find(item=>item.id===targetBlock.formId):null; if(targetBlock&&form&&(targetBlock.formMode||'modal')==='page')href=this.formUrl(form.publicId); if(targetBlock&&form&&(targetBlock.formMode||'modal')==='modal')modal=` data-nexa-form-open="${this.escape(targetBlock.id)}" aria-haspopup="dialog"`; const target=block.buttonNewTab?' target="_blank" rel="noopener"':''; return `<a class="nexa-preview-button" href="${this.escape(href)}"${modal}${target}>${this.escape(label)}</a>`; }
    linkedFormBlock(value) { const destination=String(value||''); if(destination.startsWith('#')){const id=destination.slice(1);return this.current?.blocks.find(block=>block.id===id&&block.type==='form')||null;} const publicId=this.formPublicId(destination); const form=this.forms.find(item=>item.publicId===publicId); return form?this.current?.blocks.find(block=>block.type==='form'&&block.formId===form.id)||null:null; }
    formPreview(block,form,interactive) { if(!form)return '<div class="nexa-preview-form"><span class="fas fa-wpforms"></span> Choose a published form</div>'; const mode=block.formMode||'modal'; const url=this.formUrl(form.publicId); const frameUrl=`${url}&nexaFrame=1`; const label=this.escape(block.formButtonLabel||'Open form'); if(mode==='embedded')return `<iframe class="nexa-preview-form-frame ${interactive?'is-canvas':''}" title="${this.escape(block.heading||form.name||'Contact form')}" src="${this.escape(frameUrl)}" loading="lazy"></iframe>`; if(mode==='page')return `<div class="nexa-preview-form-action"><span><strong>Separate form page</strong><small>The form opens with room for longer questions.</small></span><a class="nexa-preview-button" href="${this.escape(url)}"${interactive?' tabindex="-1"':' target="_blank" rel="noopener"'}>${label}</a></div>`; const dialog=interactive?'':`<dialog class="nexa-preview-form-dialog" data-nexa-form-dialog="${this.escape(block.id)}"><header><strong>${this.escape(block.heading||form.name||'Contact form')}</strong><button type="button" data-nexa-form-close aria-label="Close">&times;</button></header><iframe title="${this.escape(block.heading||form.name||'Contact form')}" src="${this.escape(frameUrl)}" loading="lazy"></iframe></dialog>`; return `<div class="nexa-preview-form-action"><span><strong>Popup form</strong><small>Opens without leaving the landing page.</small></span><button class="nexa-preview-button" type="button" data-nexa-form-open="${this.escape(block.id)}"${interactive?' disabled':''}>${label}</button></div>${dialog}`; }
    formUrl(publicId) { const base=window.location.pathname.split('/w/')[0].replace(/\/$/,''); return `${window.location.origin}${base}/?entryPoint=LeadCaptureForm&id=${encodeURIComponent(publicId)}`; }
    templateImageUrl(name) { const base=window.location.pathname.split('/w/')[0].replace(/\/$/,''); return `${window.location.origin}${base}/client/custom/img/landing-templates/${encodeURIComponent(name)}`; }

    inlineEdit(event) { const node=event.currentTarget; const block=this.current?.blocks.find(item=>item.id===node.dataset.blockId); if(!block)return; const value=node.innerText.replace(/\u00a0/g,' ').trim(); const index=node.dataset.inlineItemIndex; if(index!==undefined){block.items||=[]; if(block.items[Number(index)])block.items[Number(index)][node.dataset.inlineField]=value;}else block[node.dataset.inlineField]=value; if(this.selectedBlockId===block.id)this.fillBlockSettings(block.id); }
    inlineKeydown(event) { if(event.key==='Escape'){event.preventDefault();this.renderCanvas();return;} if(event.key==='Enter'&&event.currentTarget.dataset.singleLine){event.preventDefault();event.currentTarget.blur();} }
    chooseBlockImage(event) { event.preventDefault();event.stopPropagation(); const section=event.currentTarget.closest('[data-select-block]'); this.pendingImageBlockId=section?.dataset.selectBlock||this.selectedBlockId; const input=this.element.querySelector('[data-landing-image-upload]'); input.value=''; input.click(); }
    async uploadBlockImage(event) { const file=event.currentTarget.files?.[0]; const block=this.current?.blocks.find(item=>item.id===this.pendingImageBlockId); if(!file||!block)return; if(!/^image\/(jpeg|png|webp|gif)$/i.test(file.type))return Espo.Ui.error('Choose a JPG, PNG, WebP or GIF image.'); if(file.size>8*1024*1024)return Espo.Ui.error('Images cannot be larger than 8 MB.'); Espo.Ui.notifyWait(); try{const data=await this.filePayload(file); const response=await Espo.Ajax.postRequest('Nexa/assets',{displayName:file.name.replace(/\.[^.]+$/,''),description:'Landing page image',altText:block.altText||'',locale:this.current.locale||'en',accessScope:'public',folderId:null,tags:['landing-page'],fileName:file.name,mimeType:file.type,...data}); const workspace=await Espo.Ajax.getRequest('Nexa/landing-pages/workspace'); this.assets=workspace.assets||[]; this.populateChoices(); block.assetId=response.id; block.templateImage=null; await this.ensureAssetPreview(response.id); this.selectedBlockId=block.id; this.renderCanvas(); this.fillBlockSettings(block.id); Espo.Ui.success('Image added to the tenant Asset Library');}catch(error){Espo.Ui.error(error?.message||'The image could not be uploaded.');}finally{this.pendingImageBlockId=null;Espo.Ui.notify(false);} }
    filePayload(file) { return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({data:String(reader.result||'')});reader.onerror=reject;reader.readAsDataURL(file);}); }
    async ensureAssetPreview(id) { if(!id||this.assetPreviewUrls.has(id))return; try{const file=await Espo.Ajax.getRequest(`Nexa/assets/${encodeURIComponent(id)}/download`); if(file?.data)this.assetPreviewUrls.set(id,`data:${file.mimeType||'application/octet-stream'};base64,${file.data}`);}catch(error){console.warn('Landing page asset preview unavailable.',error);} }

    settingsTab(event) { const tab = event.currentTarget.dataset.settingsTab; this.element.querySelectorAll('[data-settings-tab]').forEach(node => node.classList.toggle('is-active', node.dataset.settingsTab === tab)); this.element.querySelector('[data-page-settings]').hidden = tab !== 'page'; this.element.querySelector('[data-block-settings]').hidden = tab !== 'block'; }
    payload() { const form = this.element.querySelector('[data-page-settings]'); form.dispatchEvent(new Event('input',{bubbles:true})); return {...this.current,id:undefined,status:undefined}; }
    async savePage() { try { this.error(''); Espo.Ui.notifyWait(); const response = this.current.id ? await Espo.Ajax.putRequest(`Nexa/landing-pages/${encodeURIComponent(this.current.id)}`,this.payload()) : await Espo.Ajax.postRequest('Nexa/landing-pages',this.payload()); this.current.id = response.id; await this.load(); const refreshed=this.pages.find(item=>item.id===response.id); if(refreshed) this.current={...refreshed.configuration,id:refreshed.id,status:refreshed.status}; this.element.querySelector('[data-landing-list]').hidden=true; this.element.querySelector('[data-landing-editor]').hidden=false; Espo.Ui.success('Draft saved'); return response.id; } catch(error){this.error(error?.message||'The landing page could not be saved.');return null;} finally{Espo.Ui.notify(false);} }
    async publishPage() { const id = await this.savePage(); if(!id) return; try { Espo.Ui.notifyWait(); const response=await Espo.Ajax.postRequest(`Nexa/landing-pages/${encodeURIComponent(id)}/publish`); await this.load(); this.backToPages(); Espo.Ui.success('Landing page published'); if(response.url) window.open(response.url,'_blank','noopener'); } catch(error){this.error(error?.message||'The landing page could not be published.');} finally{Espo.Ui.notify(false);} }

    async previewDraft() { await Promise.all((this.current?.blocks||[]).map(block=>block.assetId?this.ensureAssetPreview(block.assetId):null)); const dialog=this.element.querySelector('[data-preview-dialog]'); dialog.querySelector('[data-preview-frame]').srcdoc=this.previewDocument(); this.dialog(dialog,true); }
previewDocument() { const body=this.current.blocks.map(block=>this.blockPreview(block,false)).join(''); const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;color:${this.current.textColor};background:${this.current.backgroundColor};line-height:1.55}section{padding:72px max(24px,calc((100vw - 1040px)/2))}.nexa-preview-block.is-hero{display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:52px;min-height:78vh}.nexa-preview-block.is-hero h1{font-size:clamp(42px,6vw,70px);line-height:1.03;margin:12px 0 18px}.nexa-preview-block h2{font-size:clamp(30px,4vw,46px);margin:8px 0 12px}.nexa-preview-block p{white-space:pre-line;color:color-mix(in srgb,${this.current.textColor} 72%,transparent);font-size:17px}.nexa-preview-block small{color:${this.current.primaryColor};font-weight:750;text-transform:uppercase}.nexa-preview-button{display:inline-block;padding:12px 18px;background:${this.current.primaryColor};color:white;border-radius:5px;font-weight:700;text-decoration:none;cursor:pointer}.nexa-preview-photo{height:560px}.nexa-preview-photo img{width:100%;height:100%;object-fit:cover;border-radius:8px}.nexa-preview-items{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin-top:34px}.nexa-preview-items article{border-top:3px solid ${this.current.primaryColor};padding-top:20px}.nexa-preview-items article strong{font-size:20px}.nexa-preview-items.is-stats article strong{display:block;color:${this.current.primaryColor};font-size:40px}.is-stats{background:color-mix(in srgb,${this.current.primaryColor} 7%,${this.current.backgroundColor})}.is-testimonial{background:${this.current.textColor};color:${this.current.backgroundColor}}.is-testimonial blockquote{margin:0;max-width:900px;font-size:clamp(30px,4vw,52px);font-weight:700;line-height:1.18}.is-testimonial p{color:color-mix(in srgb,${this.current.backgroundColor} 75%,transparent)}.is-form{display:grid;grid-template-columns:.75fr 1.25fr;gap:44px;background:color-mix(in srgb,${this.current.primaryColor} 6%,${this.current.backgroundColor})}.nexa-preview-form{display:grid;min-height:360px;place-items:center;border:1px solid #ccd7d8;background:white}.nexa-preview-form-frame{width:100%;min-height:590px;border:1px solid #ccd7d8;background:white;border-radius:7px}.is-cta{display:flex;align-items:center;justify-content:space-between;gap:30px;background:color-mix(in srgb,${this.current.primaryColor} 11%,${this.current.backgroundColor})}@media(max-width:720px){section{padding:48px 20px}.nexa-preview-block.is-hero,.is-form{grid-template-columns:1fr}.nexa-preview-photo{height:400px}.nexa-preview-items{grid-template-columns:1fr}.is-cta{align-items:flex-start;flex-direction:column}}`; return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body>${body}</body></html>`; }
    closePreview() { this.dialog(this.element.querySelector('[data-preview-dialog]'),false); }
    openPage(event) { const page=this.pages.find(item=>item.id===event.currentTarget.dataset.id); if(page?.url) window.open(page.url,'_blank','noopener'); }
    askArchive(event) { const page=this.pages.find(item=>item.id===event.currentTarget.dataset.id); if(!page)return; this.pendingArchive=page; this.element.querySelector('[data-archive-copy]').textContent=`Archive “${page.name}”?`; this.dialog(this.element.querySelector('[data-archive-dialog]'),true); }
    closeArchive() { this.dialog(this.element.querySelector('[data-archive-dialog]'),false); this.pendingArchive=null; }
    async confirmArchive() { if(!this.pendingArchive)return; try{await Espo.Ajax.postRequest(`Nexa/landing-pages/${encodeURIComponent(this.pendingArchive.id)}/archive`);this.closeArchive();await this.load();Espo.Ui.success('Landing page archived');}catch(error){Espo.Ui.error(error?.message||'The page could not be archived.');} }
    dialog(node,open){if(!node)return;node.hidden=!open;node.style.display=open?'flex':'none';node.setAttribute('aria-hidden',open?'false':'true');}
    error(message){const node=this.element.querySelector('[data-builder-error]');node.textContent=message;node.hidden=!message;}
    slug(value){return String(value||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,160);}
    title(value){return String(value||'').replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());}
    date(value){if(!value)return 'Not recorded';const date=new Date(value.replace(' ','T')+'Z');return Number.isNaN(date.getTime())?this.escape(value):new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(date);}
    escape(value){const node=document.createElement('div');node.textContent=String(value??'');return node.innerHTML;}
});
