<main class="nexa-segment-workspace">
    <header class="nexa-segment-heading">
        <div><p>Marketing</p><h1>Segments</h1><span>Build governed audiences that stay aligned with your CRM and consent data.</span></div>
        <button class="btn btn-primary" type="button" data-action="new-segment"><span class="fas fa-plus" aria-hidden="true"></span>Create segment</button>
    </header>
    <section class="nexa-segment-state" data-segment-state="loading"><span class="fas fa-circle-notch fa-spin" aria-hidden="true"></span><strong>Loading segments</strong></section>
    <section class="nexa-segment-state" data-segment-state="error" hidden><span class="fas fa-exclamation-circle" aria-hidden="true"></span><strong>Segments could not be loaded.</strong><button class="btn btn-default" data-action="reload">Try again</button></section>
    <div data-segment-state="ready" hidden>
        <section class="nexa-segment-summary" aria-label="Segment summary"><div><span>Total segments</span><strong data-summary-total>0</strong></div><div><span>Total memberships</span><strong data-summary-members>0</strong></div><div><span>Marketable by email</span><strong data-summary-eligible>0</strong></div><div><span>Suppressed</span><strong data-summary-suppressed>0</strong></div></section>
        <div class="nexa-segment-toolbar">
            <label><span class="fas fa-search" aria-hidden="true"></span><input class="form-control" type="search" data-segment-search placeholder="Search segments" aria-label="Search segments"></label>
            <select class="form-control" data-segment-type aria-label="Filter by segment type"><option value="">All types</option><option value="dynamic">Active segments</option><option value="static">Static segments</option></select>
            <select class="form-control" data-segment-folder aria-label="Filter by folder"><option value="">All folders</option></select><strong data-segment-count>0 segments</strong>
        </div>
        <div class="nexa-segment-table-wrap" role="region" aria-label="Segments" tabindex="0"><table class="table" data-workspace-table="segments"><thead><tr><th>Segment</th><th>Type</th><th>Folder</th><th>Members</th><th>Marketable</th><th>Suppressed</th><th>Last processed</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody data-segment-list></tbody></table></div>
        <section class="nexa-segment-empty" data-segment-empty hidden><span class="fas fa-filter" aria-hidden="true"></span><h2>Create your first segment</h2><p>Build an active audience from CRM rules or save a fixed group for one-time use.</p><button class="btn btn-primary" data-action="new-segment">Create segment</button></section>
    </div>
    <div class="nexa-segment-editor" data-segment-editor hidden>
        <div class="nexa-segment-dialog" role="dialog" aria-modal="true" aria-labelledby="nexa-segment-title">
            <header><div><p>Segment builder</p><h2 id="nexa-segment-title" data-editor-title>Create segment</h2></div><button class="btn btn-icon" type="button" data-action="close-editor" title="Close"><span class="fas fa-times" aria-hidden="true"></span></button></header>
            <nav class="nexa-segment-steps" aria-label="Segment creation steps"><button type="button" data-action="go-step" data-step="1"><span>1</span>Audience</button><button type="button" data-action="go-step" data-step="2"><span>2</span>Filters</button><button type="button" data-action="go-step" data-step="3"><span>3</span>Details</button></nav>
            <form data-segment-form novalidate>
                <div class="nexa-segment-stage" data-builder-step="1">
                    <div class="nexa-segment-stage-copy"><span class="fas fa-users"></span><div><h3>Who should this segment contain?</h3><p>Start with the CRM records and membership behaviour.</p></div></div>
                    <fieldset class="nexa-segment-record-type"><legend>Record type</legend><label><input type="radio" name="recordType" value="Contact" checked><span class="fas fa-address-card"></span><strong>Contacts</strong><small>People and their associated company properties</small></label></fieldset>
                    <fieldset class="nexa-segment-type-cards"><legend>Membership type</legend><label><input type="radio" name="type" value="dynamic" checked><span><i class="fas fa-bolt"></i><strong>Active segment</strong><small>Contacts enter and leave automatically whenever their CRM data matches or stops matching.</small></span></label><label><input type="radio" name="type" value="static"><span><i class="fas fa-camera"></i><strong>Static segment</strong><small>Create a fixed snapshot from filters, or start empty and manage members manually.</small></span></label></fieldset>
                    <label class="nexa-segment-snapshot" data-static-snapshot hidden><input type="checkbox" name="snapshotFromRules" checked><span><strong>Build the initial list from filters</strong><small>Matching contacts are added once when saved. Membership then remains manual.</small></span></label>
                </div>
                <div class="nexa-segment-stage" data-builder-step="2" hidden>
                    <div class="nexa-segment-builder-grid"><section class="nexa-segment-rules"><div class="nexa-segment-rule-heading"><div><h3>Include contacts when</h3><p>Use CRM properties to define who belongs.</p></div><select class="form-control" name="matchMode"><option value="all">All filters match (AND)</option><option value="any">Any filter matches (OR)</option></select></div><div data-segment-rules></div><button class="btn btn-default btn-sm" type="button" data-action="add-rule"><span class="fas fa-plus"></span>Add filter</button><section class="nexa-segment-exclusions"><div><h3>Exclusions</h3><p>Matching contacts are removed even when they meet the inclusion filters.</p></div><div data-exclusion-rules></div><button class="btn btn-default btn-sm" type="button" data-action="add-exclusion"><span class="fas fa-minus-circle"></span>Add exclusion</button></section><div class="nexa-segment-behavior-note" data-behavior-note><span class="fas fa-info-circle"></span><p></p></div></section><aside class="nexa-segment-preview"><header><div><h3>Test matches</h3><p>Preview real contacts before saving.</p></div><button class="btn btn-default btn-sm" type="button" data-action="preview-segment"><span class="fas fa-play"></span>Preview</button></header><div class="nexa-segment-preview-counts"><div><strong data-preview-members>0</strong><span>Matched</span></div><div><strong data-preview-eligible>0</strong><span>Marketable</span></div><div><strong data-preview-suppressed>0</strong><span>Suppressed</span></div></div><div class="nexa-segment-preview-list" data-preview-list><p>Add filters and run a preview.</p></div></aside></div>
                </div>
                <div class="nexa-segment-stage" data-builder-step="3" hidden><div class="nexa-segment-details"><div><h3>Name and organize this segment</h3><p>Clear names and folders make audiences easier for the whole team to reuse safely.</p></div><label><span>Name <b>*</b></span><input class="form-control" name="name" maxlength="255" required placeholder="Example: UK marketing leads"><em data-segment-error="name"></em></label><label><span>Description</span><textarea class="form-control" name="description" maxlength="1000" rows="4" placeholder="Explain who this segment contains and how it will be used."></textarea></label><label><span>Folder</span><input class="form-control" name="folder" maxlength="120" list="nexa-segment-folders" placeholder="Example: Sales audiences"><datalist id="nexa-segment-folders" data-folder-options></datalist></label><label><span>Access</span><select class="form-control" name="accessLevel"><option value="everyone">Everyone in this workspace</option><option value="owner">Only the owner and administrators</option><option value="admins">Administrators only</option></select></label><div class="nexa-segment-review" data-segment-review></div></div></div>
                <footer><span data-editor-status></span><button class="btn btn-default" type="button" data-action="previous-step"><span class="fas fa-arrow-left"></span>Back</button><button class="btn btn-primary" type="button" data-action="next-step">Continue<span class="fas fa-arrow-right"></span></button><button class="btn btn-primary" type="submit" data-action="save-segment" hidden><span class="fas fa-save"></span>Save and process</button></footer>
            </form>
        </div>
    </div>
</main>
