<?php
namespace Espo\Custom\Tools\Event;
use Espo\Core\Exceptions\BadRequest; use Espo\Core\ORM\EntityManager; use Espo\Core\Tenant\TenantContextStore; use stdClass;
/** Replay-safe behavioral event ingestion projected to the existing timeline and outbox. */
final class BehaviorEventService {
 public function __construct(private EntityManager $em,private TenantContextStore $store,private EventContract $contract){}
 public function ingest(stdClass $in): array {
  $c=$this->store->require();$event=$this->contract->normalize($in);$pdo=$this->em->getPDO();
  $find=$pdo->prepare('SELECT id FROM nexa_behavior_event WHERE tenant_id=? AND service_id=? AND source=? AND idempotency_key=?');$find->execute([$c->tenantId,$c->serviceId,$event['source'],$event['idempotencyKey']]);if($id=$find->fetchColumn())return ['id'=>$id,'duplicate'=>true];
  $contact=$this->owned('contact',$event['contactId']);$account=$this->owned('account',$event['accountId']);$correlation=$event['correlationId']??$this->uuid();$id=$this->uuid();$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
  try{$visitor=$this->visitor($event['visitorKey'],$contact,$event['occurredAt'],$event['identityMethod'],$event['identityEvidenceHash'],$id);$properties=$this->json($event['properties']);$consent=$this->json($event['consent']);
   $pdo->prepare('INSERT INTO nexa_behavior_event (id,tenant_id,service_id,event_type,event_version,event_category,consent_category,source,idempotency_key,correlation_id,visitor_identity_id,contact_id,account_id,session_key_hash,page_url,referrer_url,properties_json,consent_json,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$c->tenantId,$c->serviceId,$event['eventType'],$event['eventVersion'],$event['eventCategory'],$event['consentCategory'],$event['source'],$event['idempotencyKey'],$correlation,$visitor,$contact,$account,$this->hash($event['sessionKey']),$event['pageUrl'],$event['referrerUrl'],$properties,$consent,$event['occurredAt']]);
   if($contact||$account)$pdo->prepare("INSERT INTO nexa_timeline_event (id,tenant_id,contact_id,account_id,event_type,source_entity_type,source_entity_id,source_occurred_at,actor_type,visibility,correlation_id,summary,metadata_json) VALUES (?,?,?,?,?,'BehaviorEvent',?,?,'system','internal',?,?,?)")->execute([$this->uuid(),$c->tenantId,$contact,$account,$event['eventType'],$id,$event['occurredAt'],$correlation,$event['summary'],$properties]);
   $pdo->prepare("INSERT INTO nexa_outbox_event (id,tenant_id,service_id,event_type,aggregate_type,aggregate_id,payload_json,correlation_id) VALUES (?,?,?,'behavior.event.recorded','BehaviorEvent',?,?,?)")->execute([$this->uuid(),$c->tenantId,$c->serviceId,$id,json_encode(['eventId'=>$id,'eventType'=>$event['eventType'],'contactId'=>$contact,'accountId'=>$account],JSON_THROW_ON_ERROR),$correlation]);if($owns)$pdo->commit();
  }catch(\PDOException $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();if((string)$e->getCode()==='23000'){$find->execute([$c->tenantId,$c->serviceId,$event['source'],$event['idempotencyKey']]);if($found=$find->fetchColumn())return ['id'=>$found,'duplicate'=>true];}throw $e;}catch(\Throwable $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();throw $e;}
  return ['id'=>$id,'duplicate'=>false,'correlationId'=>$correlation,'identified'=>(bool)$contact];
 }
 private function visitor(mixed $raw,?string $contact,string $at,?string $method,?string $evidence,string $eventId):?string{$hash=$this->hash($raw);if(!$hash)return null;$legacyHash=hash('sha256',(string)$raw);$c=$this->store->require();$p=$this->em->getPDO();$q=$p->prepare('SELECT id,contact_id,visitor_key_hash FROM nexa_visitor_identity WHERE tenant_id=? AND service_id=? AND visitor_key_hash IN (?,?) ORDER BY visitor_key_hash=? DESC LIMIT 1 FOR UPDATE');$q->execute([$c->tenantId,$c->serviceId,$hash,$legacyHash,$hash]);$row=$q->fetch(\PDO::FETCH_ASSOC);if($row){if($contact&&$row['contact_id']&&$row['contact_id']!==$contact)throw new BadRequest('This visitor is already linked to a different contact.');$p->prepare('UPDATE nexa_visitor_identity SET visitor_key_hash=?,last_seen_at=?,identified_at=IF(identified_at IS NULL AND ? IS NOT NULL,?,identified_at),resolution_method=COALESCE(resolution_method,?),resolution_evidence_hash=COALESCE(resolution_evidence_hash,?),resolved_by_event_id=COALESCE(resolved_by_event_id,?),contact_id=COALESCE(contact_id,?) WHERE id=?')->execute([$hash,$at,$contact,$at,$method,$evidence,$contact?$eventId:null,$contact,$row['id']]);return(string)$row['id'];}$id=$this->uuid();$p->prepare('INSERT INTO nexa_visitor_identity (id,tenant_id,service_id,visitor_key_hash,contact_id,first_seen_at,last_seen_at,identified_at,resolution_method,resolution_evidence_hash,resolved_by_event_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$c->tenantId,$c->serviceId,$hash,$contact,$at,$at,$contact?$at:null,$method,$evidence,$contact?$eventId:null]);return$id;}
 private function owned(string $table,mixed $id):?string{if(!$id)return null;$c=$this->store->require();$q=$this->em->getPDO()->prepare("SELECT id FROM {$table} WHERE id=? AND tenant_id=? AND service_id=? AND deleted=0");$q->execute([$id,$c->tenantId,$c->serviceId]);if(!$q->fetchColumn())throw new BadRequest('The related CRM record is unavailable.');return$id;}
 private function hash(mixed $v):?string{if(!$v)return null;$c=$this->store->require();return hash('sha256',$c->tenantId."\0".$c->serviceId."\0".$v);} private function json(mixed $v):string{return json_encode((object)$v,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);} private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
