<?php
namespace Espo\Custom\Tools\Event;
use Espo\Core\Exceptions\BadRequest; use Espo\Core\ORM\EntityManager; use Espo\Core\Tenant\TenantContextStore; use stdClass;
/** Replay-safe behavioral event ingestion projected to the existing timeline and outbox. */
final class BehaviorEventService {
 public function __construct(private EntityManager $em,private TenantContextStore $store){}
 public function ingest(stdClass $in): array {
  $c=$this->store->require();$type=$this->req($in->eventType??null,128,'Enter an event type.');$source=$this->req($in->source??'api',64,'Enter an event source.');$key=$this->req($in->idempotencyKey??null,191,'Provide an idempotency key.');$pdo=$this->em->getPDO();
  $find=$pdo->prepare('SELECT id FROM nexa_behavior_event WHERE tenant_id=? AND service_id=? AND source=? AND idempotency_key=?');$find->execute([$c->tenantId,$c->serviceId,$source,$key]);if($id=$find->fetchColumn())return ['id'=>$id,'duplicate'=>true];
  $contact=$this->owned('contact',$in->contactId??null);$account=$this->owned('account',$in->accountId??null);$at=$this->date($in->occurredAt??null);$correlation=$this->uuidValue($in->correlationId??null)??$this->uuid();$visitor=$this->visitor($in->visitorKey??null,$contact,$at);$id=$this->uuid();$properties=$this->json($in->properties??new stdClass());$consent=$this->json($in->consent??new stdClass());$owns=!$pdo->inTransaction();if($owns)$pdo->beginTransaction();
  try{$pdo->prepare('INSERT INTO nexa_behavior_event (id,tenant_id,service_id,event_type,event_version,source,idempotency_key,correlation_id,visitor_identity_id,contact_id,account_id,session_key_hash,page_url,referrer_url,properties_json,consent_json,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$c->tenantId,$c->serviceId,$type,max(1,min(65535,(int)($in->eventVersion??1))),$source,$key,$correlation,$visitor,$contact,$account,$this->hash($in->sessionKey??null),$this->text($in->pageUrl??null,2048),$this->text($in->referrerUrl??null,2048),$properties,$consent,$at]);
   if($contact||$account)$pdo->prepare("INSERT INTO nexa_timeline_event (id,tenant_id,contact_id,account_id,event_type,source_entity_type,source_entity_id,source_occurred_at,actor_type,visibility,correlation_id,summary,metadata_json) VALUES (?,?,?,?,?,'BehaviorEvent',?,?,'system','internal',?,?,?)")->execute([$this->uuid(),$c->tenantId,$contact,$account,$type,$id,$at,$correlation,$this->text($in->summary??$type,255),$properties]);
   $pdo->prepare("INSERT INTO nexa_outbox_event (id,tenant_id,service_id,event_type,aggregate_type,aggregate_id,payload_json,correlation_id) VALUES (?,?,?,'behavior.event.recorded','BehaviorEvent',?,?,?)")->execute([$this->uuid(),$c->tenantId,$c->serviceId,$id,json_encode(['eventId'=>$id,'eventType'=>$type,'contactId'=>$contact,'accountId'=>$account],JSON_THROW_ON_ERROR),$correlation]);if($owns)$pdo->commit();
  }catch(\PDOException $e){if($owns&&$pdo->inTransaction())$pdo->rollBack();if((string)$e->getCode()==='23000'){$find->execute([$c->tenantId,$c->serviceId,$source,$key]);if($found=$find->fetchColumn())return ['id'=>$found,'duplicate'=>true];}throw $e;}
  return ['id'=>$id,'duplicate'=>false,'correlationId'=>$correlation,'identified'=>(bool)$contact];
 }
 private function visitor(mixed $raw,?string $contact,string $at):?string{$hash=$this->hash($raw);if(!$hash)return null;$c=$this->store->require();$p=$this->em->getPDO();$q=$p->prepare('SELECT id FROM nexa_visitor_identity WHERE tenant_id=? AND service_id=? AND visitor_key_hash=?');$q->execute([$c->tenantId,$c->serviceId,$hash]);if($id=$q->fetchColumn()){$p->prepare('UPDATE nexa_visitor_identity SET last_seen_at=?,contact_id=COALESCE(contact_id,?),identified_at=IF(contact_id IS NULL AND ? IS NOT NULL,NOW(6),identified_at) WHERE id=?')->execute([$at,$contact,$contact,$id]);return(string)$id;}$id=$this->uuid();$p->prepare('INSERT INTO nexa_visitor_identity (id,tenant_id,service_id,visitor_key_hash,contact_id,first_seen_at,last_seen_at,identified_at) VALUES (?,?,?,?,?,?,?,?)')->execute([$id,$c->tenantId,$c->serviceId,$hash,$contact,$at,$at,$contact?$at:null]);return$id;}
 private function owned(string $table,mixed $id):?string{$id=$this->text($id,36);if(!$id)return null;$c=$this->store->require();$q=$this->em->getPDO()->prepare("SELECT id FROM {$table} WHERE id=? AND tenant_id=? AND service_id=? AND deleted=0");$q->execute([$id,$c->tenantId,$c->serviceId]);if(!$q->fetchColumn())throw new BadRequest('The related CRM record is unavailable.');return$id;}
 private function req(mixed $v,int $m,string $e):string{$v=$this->text($v,$m);if(!$v)throw new BadRequest($e);return$v;} private function text(mixed $v,int $m):?string{$v=trim((string)($v??''));return$v===''?null:mb_substr($v,0,$m);} private function hash(mixed $v):?string{$v=$this->text($v,500);return$v?hash('sha256',$v):null;} private function json(mixed $v):string{return json_encode((object)$v,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);} private function date(mixed $v):string{if(!$v)return date('Y-m-d H:i:s.u');try{return(new \DateTimeImmutable((string)$v))->format('Y-m-d H:i:s.u');}catch(\Throwable){throw new BadRequest('Enter a valid event date and time.');}} private function uuidValue(mixed $v):?string{$v=$this->text($v,36);return$v&&preg_match('/^[0-9a-f-]{36}$/i',$v)?$v:null;} private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
