<section class="nexa-landing-workspace">
    <div data-landing-list>
        <header class="nexa-landing-header"><div><span class="nexa-landing-eyebrow">Marketing content</span><h1>Landing Pages</h1><p>Create focused, measurable pages using governed forms and assets.</p></div><button class="btn btn-primary" type="button" data-action="new-page"><span class="fas fa-plus"></span> New landing page</button></header>
        <div data-landing-state="loading" class="nexa-landing-state"><span class="fas fa-circle-notch fa-spin"></span> Loading landing pages</div>
        <div data-landing-state="error" class="nexa-landing-state is-error" hidden><strong>Landing pages could not be loaded.</strong><button class="btn btn-default" data-action="reload">Try again</button></div>
        <div data-landing-state="ready" hidden>
            <div class="nexa-landing-toolbar"><label class="nexa-landing-search"><span class="fas fa-search"></span><span class="sr-only">Search landing pages</span><input class="form-control" type="search" placeholder="Search landing pages" data-page-search></label><label><span class="sr-only">Status</span><select class="form-control" data-page-status><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><strong data-page-total>0 pages</strong></div>
            <div class="nexa-landing-table-wrap" role="region" aria-label="Landing pages" tabindex="0"><table class="table" data-workspace-table="landing-pages"><thead><tr><th data-column="name"><button data-page-sort="name">Page</button></th><th data-column="status"><button data-page-sort="status">Status</button></th><th data-column="locale">Language</th><th data-column="views"><button data-page-sort="views">Views</button></th><th data-column="clicks"><button data-page-sort="clicks">Clicks</button></th><th data-column="modifiedAt"><button data-page-sort="modifiedAt">Updated</button></th><th data-column="actions"><span class="sr-only">Actions</span></th></tr></thead><tbody data-page-rows></tbody></table></div>
        </div>
    </div>

    <div data-template-gallery hidden>
        <header class="nexa-template-header"><div><button class="btn btn-icon" type="button" data-action="close-templates" title="Back to landing pages"><span class="fas fa-arrow-left"></span></button><div><span class="nexa-landing-eyebrow">Start with a complete page</span><h1>Choose a landing page design</h1><p>Every design is ready to publish after you connect a form and review the details.</p></div></div><button class="btn btn-default" type="button" data-action="start-blank"><span class="fas fa-plus"></span> Start from blank</button></header>
        <div class="nexa-template-notice" data-template-form-notice hidden><span class="fas fa-info-circle"></span><span>You can start designing now. Create and publish a form before you publish the page.</span></div>
        <div class="nexa-template-grid" data-template-grid></div>
    </div>

    <div data-landing-editor hidden>
        <input type="file" accept="image/jpeg,image/png,image/webp,image/gif" data-landing-image-upload hidden>
        <header class="nexa-builder-header"><div><button class="btn btn-icon" type="button" data-action="back-to-pages" title="Back to landing pages"><span class="fas fa-arrow-left"></span></button><div><span class="nexa-landing-eyebrow">Landing page builder</span><h1 data-builder-title>New landing page</h1></div></div><div class="nexa-builder-actions"><button class="btn btn-default" type="button" data-action="preview-page"><span class="fas fa-eye"></span> Preview</button><button class="btn btn-default" type="button" data-action="save-page"><span class="fas fa-save"></span> Save draft</button><button class="btn btn-primary" type="button" data-action="publish-page"><span class="fas fa-paper-plane"></span> Publish</button></div></header>
        <div class="nexa-builder-error" data-builder-error hidden></div>
        <div class="nexa-builder-grid">
            <aside class="nexa-block-palette"><h2>Add content</h2><p>Choose a block, then edit it in Page settings.</p><button type="button" data-add-block="hero"><span class="fas fa-window-maximize"></span><strong>Hero</strong></button><button type="button" data-add-block="features"><span class="fas fa-th-large"></span><strong>Features</strong></button><button type="button" data-add-block="stats"><span class="fas fa-chart-bar"></span><strong>Statistics</strong></button><button type="button" data-add-block="testimonial"><span class="fas fa-quote-left"></span><strong>Testimonial</strong></button><button type="button" data-add-block="text"><span class="fas fa-align-left"></span><strong>Text</strong></button><button type="button" data-add-block="image"><span class="fas fa-image"></span><strong>Image</strong></button><button type="button" data-add-block="form"><span class="fas fa-wpforms"></span><strong>Form</strong></button><button type="button" data-add-block="cta"><span class="fas fa-bullhorn"></span><strong>Call to action</strong></button><button type="button" data-add-block="divider"><span class="fas fa-minus"></span><strong>Divider</strong></button></aside>
            <main class="nexa-builder-canvas" data-builder-canvas aria-label="Landing page preview"></main>
            <aside class="nexa-builder-settings">
                <div class="nexa-settings-tabs"><button class="is-active" type="button" data-settings-tab="page">Page</button><button type="button" data-settings-tab="block">Block</button></div>
                <form data-page-settings>
                    <label><span>Internal page name *</span><input class="form-control" name="name" maxlength="160" required></label><label><span>URL path *</span><div class="nexa-slug-input"><span>/</span><input class="form-control" name="slug" maxlength="160" required></div></label><label><span>Language</span><input class="form-control" name="locale" value="en" maxlength="16"></label>
                    <h3>Search and sharing</h3><label><span>Page title *</span><input class="form-control" name="seoTitle" maxlength="70" required></label><label><span>Meta description</span><textarea class="form-control" name="seoDescription" maxlength="180" rows="3"></textarea></label><label><span>Canonical URL</span><input class="form-control" name="canonicalUrl" type="url" placeholder="https://example.com/page"></label><label class="nexa-check"><input type="checkbox" name="noIndex"> Hide from search engines</label>
                    <h3>Theme</h3><div class="nexa-color-row"><label><span>Brand</span><input name="primaryColor" type="color" value="#087d71"></label><label><span>Background</span><input name="backgroundColor" type="color" value="#ffffff"></label><label><span>Text</span><input name="textColor" type="color" value="#172f35"></label></div>
                </form>
                <form data-block-settings hidden><div class="nexa-selected-type" data-selected-type>No block selected</div><label data-block-field="eyebrow"><span>Eyebrow</span><input class="form-control" name="eyebrow" maxlength="100"></label><label data-block-field="heading"><span>Heading</span><input class="form-control" name="heading" maxlength="200"></label><label data-block-field="text"><span>Body text</span><textarea class="form-control" name="text" maxlength="2000" rows="6"></textarea></label><label data-block-field="itemsText"><span>Items</span><textarea class="form-control" name="itemsText" rows="8" placeholder="Title | Description | Detail"></textarea><small>Use one item per line. Separate the title, description and optional detail with |.</small></label><label data-block-field="assetId"><span>Public asset</span><select class="form-control" name="assetId" data-page-assets><option value="">Choose an asset</option></select></label><label data-block-field="altText"><span>Alternative text</span><input class="form-control" name="altText" maxlength="500"></label><label data-block-field="caption"><span>Caption</span><input class="form-control" name="caption" maxlength="300"></label><label data-block-field="formId"><span>Published form</span><select class="form-control" name="formId" data-page-forms><option value="">Choose a form</option></select></label><label data-block-field="formMode"><span>Display form</span><select class="form-control" name="formMode"><option value="modal">Popup</option><option value="embedded">Embedded on the page</option><option value="page">Separate form page</option></select><small>Popup is recommended for most Nexa forms. Use a separate page for long or complex forms.</small></label><label data-block-field="formButtonLabel"><span>Form button label</span><input class="form-control" name="formButtonLabel" maxlength="80" placeholder="Open form"></label><label data-block-field="buttonLabel"><span>Button label</span><input class="form-control" name="buttonLabel" maxlength="80"></label><label data-block-field="buttonUrl"><span>Button destination</span><input class="form-control" name="buttonUrl" placeholder="https://example.com or #form-section"></label><label class="nexa-check" data-block-field="buttonNewTab"><input type="checkbox" name="buttonNewTab"> Open destination in a new tab</label></form>
            </aside>
        </div>
    </div>
</section>

<div class="nexa-landing-modal" data-preview-dialog hidden style="display:none"><div role="dialog" aria-modal="true" aria-labelledby="landing-preview-title"><header><h2 id="landing-preview-title">Page preview</h2><button class="btn btn-icon" data-action="close-preview" title="Close" aria-label="Close"><span class="fas fa-times"></span></button></header><iframe data-preview-frame title="Landing page preview"></iframe></div></div>

<div class="nexa-landing-modal" data-archive-dialog hidden style="display:none"><div class="is-confirm" role="dialog" aria-modal="true" aria-labelledby="landing-archive-title"><header><h2 id="landing-archive-title">Archive landing page?</h2><button class="btn btn-icon" data-action="close-archive" title="Close" aria-label="Close"><span class="fas fa-times"></span></button></header><div class="nexa-confirm-copy"><p data-archive-copy></p><p>Its public URL will stop working, while published versions remain in the audit history.</p></div><footer><button class="btn btn-danger" data-action="confirm-archive">Archive page</button><button class="btn btn-default" data-action="close-archive">Cancel</button></footer></div></div>
