define('custom:views/tracking/workspace', ['view'], Dep => class extends Dep {
    template = 'custom:tracking/workspace';
    events = {
        'click [data-action="reload"]': 'load',
        'click [data-action="add-source"]': 'openCreate',
        'click [data-action="edit-source"]': 'openEdit',
        'click [data-action="close-source"]': 'closeEditor',
        'submit [data-source-form]': 'save',
        'click [data-action="copy-embed"]': 'copyEmbed',
        'click [data-action="test-source"]': 'testSource',
        'click [data-action="rotate-key"]': 'rotateKey',
    };
    setup() { this.setPageTitle('Tracking & Events'); this.workspace = null; this.current = null; }
    afterRender() { this.element?.closest('#main')?.classList.add('nexa-tracking-page'); this.load(); }
    remove() { this.element?.closest('#main')?.classList.remove('nexa-tracking-page'); super.remove(); }
    state(name) { ['loading','error','ready'].forEach(value => { const node=this.element.querySelector(`[data-tracking-state="${value}"]`); if(node)node.hidden=value!==name; }); }
    async load() { this.state('loading'); try { this.workspace=await Espo.Ajax.getRequest('Nexa/tracking/sources'); this.renderSources(); this.state('ready'); } catch(error) { this.state('error'); Espo.Ui.error(error?.message||'Tracking sources could not be loaded.'); } }
    renderSources() {
        const list=this.workspace?.sources||[]; this.element.querySelector('[data-source-total]').textContent=`${list.length} ${list.length===1?'source':'sources'}`;
        this.element.querySelector('[data-source-list]').innerHTML=list.length?list.map(item=>`<article class="nexa-tracking-source ${item.status==='paused'?'is-paused':''}"><header><span class="fas fa-wave-square"></span><div><h2>${this.escape(item.name)}</h2><p>${item.allowedOrigins.map(this.escape).join(' · ')}</p></div><span class="nexa-tracking-status">${this.escape(item.status)}</span></header><div class="nexa-tracking-metrics"><span><b>${Number(item.eventCount||0).toLocaleString()}</b>Events received</span><span><b>${this.escape(item.integrationMode.replaceAll('_',' '))}</b>Consent mode</span><span><b>${this.escape(this.date(item.lastEventAt))}</b>Last event</span></div><footer><button class="btn btn-default" type="button" data-action="test-source" data-id="${item.id}" ${item.status!=='active'?'disabled':''}><span class="fas fa-vial"></span>Send test event</button><button class="btn btn-default" type="button" data-action="copy-embed" data-id="${item.id}"><span class="fas fa-copy"></span>Copy embed code</button><button class="btn btn-default" type="button" data-action="edit-source" data-id="${item.id}"><span class="fas fa-pen"></span>Edit</button></footer></article>`).join(''):'<section class="nexa-tracking-empty"><span class="fas fa-satellite-dish"></span><h2>No tracking source yet</h2><p>Add the first approved website before installing the Nexa tracking script.</p><button class="btn btn-primary" type="button" data-action="add-source"><span class="fas fa-plus"></span>Add website</button></section>';
    }
    openCreate() { this.openEditor({name:'',status:'active',integrationMode:'managed',allowedOrigins:[]}); }
    openEdit(event) { const item=(this.workspace?.sources||[]).find(row=>row.id===event.currentTarget.dataset.id); if(item)this.openEditor(item); }
    openEditor(item) { this.current={...item}; const form=this.element.querySelector('[data-source-form]'); form.reset(); form.elements.id.value=item.id||''; form.elements.name.value=item.name||''; form.elements.status.value=item.status||'active'; form.elements.integrationMode.value=item.integrationMode||'managed'; form.elements.allowedOrigins.value=(item.allowedOrigins||[]).join('\n'); this.element.querySelector('[data-source-dialog-title]').textContent=item.id?'Edit tracking source':'Add tracking source'; this.element.querySelector('[data-source-key-row]').hidden=!item.id; form.elements.publicKey.value=item.publicKey||''; this.element.querySelector('[data-rotate-key]').hidden=!item.id; this.element.querySelector('[data-source-modal]').hidden=false; form.elements.name.focus(); }
    closeEditor() { this.element.querySelector('[data-source-modal]').hidden=true; this.current=null; }
    async save(event) { event.preventDefault(); const form=event.currentTarget; const payload={name:form.elements.name.value.trim(),status:form.elements.status.value,integrationMode:form.elements.integrationMode.value,allowedOrigins:form.elements.allowedOrigins.value.split(/[\r\n,]+/).map(v=>v.trim()).filter(Boolean)}; if(!payload.name||!payload.allowedOrigins.length)return Espo.Ui.error('Enter a name and at least one approved website origin.'); Espo.Ui.notifyWait(); try { if(form.elements.id.value)await Espo.Ajax.putRequest(`Nexa/tracking/sources/${encodeURIComponent(form.elements.id.value)}`,payload); else await Espo.Ajax.postRequest('Nexa/tracking/sources',payload); this.closeEditor(); await this.load(); Espo.Ui.success('Tracking source saved.'); } catch(error){Espo.Ui.error(error?.message||'The tracking source could not be saved.');} finally{Espo.Ui.notify(false);} }
    async copyEmbed(event) { const item=(this.workspace?.sources||[]).find(row=>row.id===event.currentTarget.dataset.id); if(!item)return; try{await navigator.clipboard.writeText(item.embedCode);Espo.Ui.success('Embed code copied.');}catch(error){Espo.Ui.error('The embed code could not be copied.');} }
    async testSource(event) { const id=event.currentTarget.dataset.id;if(!id)return;Espo.Ui.notify('Sending diagnostic event...');try{await Espo.Ajax.postRequest(`Nexa/tracking/sources/${encodeURIComponent(id)}/test`,{});await this.load();Espo.Ui.success('Diagnostic event received by the customer timeline.');}catch(error){Espo.Ui.error(error?.message||'The diagnostic event could not be recorded.');}finally{Espo.Ui.notify(false);} }
    async rotateKey() { const id=this.element.querySelector('[data-source-form]').elements.id.value; if(!id)return; if(!window.confirm('Rotate this public key? The existing website script will stop collecting until its embed code is replaced.'))return; Espo.Ui.notifyWait(); try{const item=await Espo.Ajax.postRequest(`Nexa/tracking/sources/${encodeURIComponent(id)}/rotate-key`,{});this.element.querySelector('[data-source-form]').elements.publicKey.value=item.publicKey;await this.load();Espo.Ui.success('Public key rotated. Replace the website embed code.');}catch(error){Espo.Ui.error(error?.message||'The key could not be rotated.');}finally{Espo.Ui.notify(false);} }
    date(value) { if(!value)return 'No events yet'; const parsed=new Date(String(value).replace(' ','T')+'Z'); return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString(); }
    escape(value) { const node=document.createElement('div');node.textContent=String(value??'');return node.innerHTML; }
});
