<section class="nexa-sales-workspace" aria-labelledby="nexa-sales-heading">
    <header class="nexa-sales-header">
        <div><p>Sales workspace</p><h1 id="nexa-sales-heading">{{#if isPipelines}}Pipelines{{/if}}{{#if isForecasts}}Forecasts{{/if}}{{#if isProducts}}Products & Quotes{{/if}}</h1><span>Plan revenue and move customer opportunities forward.</span></div>
        <div class="nexa-sales-header-actions"><select class="form-control" data-sales-range aria-label="Forecast period"><option value="month">This month</option><option value="quarter" selected>This quarter</option><option value="year">This year</option><option value="all">All time</option></select><button class="btn btn-default btn-icon" data-action="refreshSales" title="Refresh"><span class="fas fa-sync-alt"></span></button><a class="btn btn-primary" href="#Opportunity/create"><span class="fas fa-plus"></span> New Opportunity</a></div>
    </header>
    <nav class="nexa-sales-tabs" aria-label="Sales workspace"><a href="#NexaSales/pipelines" {{#if isPipelines}}aria-current="page"{{/if}}>Pipelines</a><a href="#NexaSales/forecasts" {{#if isForecasts}}aria-current="page"{{/if}}>Forecasts</a><a href="#NexaSales/products" {{#if isProducts}}aria-current="page"{{/if}}>Products & Quotes</a></nav>
    <div class="nexa-sales-state" data-sales-state="loading"><span class="fas fa-circle-notch fa-spin"></span><p>Loading sales workspace...</p></div>
    <div class="nexa-sales-state" data-sales-state="error" hidden><span class="fas fa-exclamation-circle"></span><h2>Sales data could not be loaded</h2><button class="btn btn-default" data-action="refreshSales">Try again</button></div>
    <div class="nexa-sales-state" data-sales-state="denied" hidden><span class="fas fa-lock"></span><h2>This sales workspace is not available for your role</h2></div>
    <div data-sales-state="ready" hidden>
        <section class="nexa-sales-metrics" data-sales-metrics aria-label="Sales totals"></section>
        {{#if isPipelines}}
        <div class="nexa-sales-section-heading"><div><p>Pipeline configuration</p><h2>Opportunity stages</h2></div><div class="nexa-pipeline-controls"><label><span class="sr-only">Active pipeline</span><select class="form-control" data-pipeline-select></select></label><div class="nexa-pipeline-actions" data-admin-only><button class="btn btn-icon" data-action="movePipeline" data-direction="-1" title="Move pipeline earlier"><span class="fas fa-arrow-up"></span></button><button class="btn btn-icon" data-action="movePipeline" data-direction="1" title="Move pipeline later"><span class="fas fa-arrow-down"></span></button><button class="btn btn-icon" data-action="editPipeline" title="Edit pipeline"><span class="fas fa-pen"></span></button><button class="btn btn-icon text-danger" data-action="archivePipeline" title="Archive pipeline"><span class="fas fa-archive"></span></button></div><form data-pipeline-form data-admin-only><input class="form-control" name="name" maxlength="160" placeholder="New pipeline name" aria-label="New pipeline name"><button class="btn btn-default" type="submit"><span class="fas fa-plus"></span> Add pipeline</button></form></div></div>
        <section class="nexa-pipeline-board" data-pipeline-board tabindex="0" aria-label="Opportunity stages"></section>
        <form class="nexa-stage-create" data-stage-create-form data-admin-only><h3>Add a stage</h3><label>Name<input class="form-control" name="name" maxlength="160" required></label><label>Probability<input class="form-control" name="probability" type="number" min="0" max="100" value="10" required></label><label>Forecast<select class="form-control" name="forecastCategory"><option>Pipeline</option><option>Best Case</option><option>Commit</option><option>Closed</option><option>Omitted</option></select></label><label><input type="checkbox" name="isClosed"> Closed stage</label><label><input type="checkbox" name="isWon"> Won stage</label><fieldset hidden><input type="checkbox" name="requiredFields" value="name" checked></fieldset><button class="btn btn-primary" type="submit"><span class="fas fa-plus"></span> Add stage</button></form>
        {{/if}}
        {{#if isForecasts}}<div class="nexa-sales-section-heading"><div><p>Revenue confidence</p><h2>Forecast categories</h2></div></div><div class="nexa-forecast-filters" data-forecast-filters aria-label="Forecast filters"></div><section class="nexa-forecast-list" data-forecast-list></section>{{/if}}
        {{#if isProducts}}<div class="nexa-sales-products-grid"><section><div class="nexa-sales-section-heading"><div><p>Commercial catalogue</p><h2>Products</h2></div></div><div class="nexa-product-list" data-product-list></div><div class="nexa-sales-section-heading nexa-quotes-heading"><div><p>Commercial history</p><h2>Recent quotes</h2></div></div><div class="nexa-product-list" data-quote-list></div></section><form class="nexa-product-form" data-product-form data-admin-only><input type="hidden" name="id"><h2 data-product-form-title>Add a product</h2><label>Name<input class="form-control" name="name" required maxlength="200"></label><label>SKU<input class="form-control" name="sku" required maxlength="100"></label><label>Description<textarea class="form-control" name="description" rows="3"></textarea></label><div><label>Unit<input class="form-control" name="unit" maxlength="40" value="each" required></label><label>Unit price<input class="form-control" name="unitPrice" type="number" min="0" step="0.01" required></label></div><div><label>Currency<select class="form-control" name="currency" required data-product-currency></select></label><label>Tax %<input class="form-control" name="taxPercent" type="number" min="0" max="100" step="0.001" value="0" required></label></div><small>Available currencies are controlled in Administration → Currency.</small><footer><button class="btn btn-primary" type="submit">Save product</button><button class="btn btn-default" type="button" data-action="cancelProductEdit">Cancel</button></footer></form></div>{{/if}}
    </div>
</section>
