define('custom:views/campaign/workspace', ['view'], Dep => class extends Dep {
    template = 'custom:campaign/workspace';
    events = {
        'click [data-action="reload"]': 'load', 'click [data-action="new-campaign"]': 'newCampaign', 'click [data-action="edit-campaign"]': 'editCampaign',
        'click [data-action="close-editor"]': 'closeEditor', 'click [data-action="preview-campaign"]': 'previewCampaign', 'click [data-action="activate-campaign"]': 'activateCampaign',
        'click [data-action="pause-campaign"]': 'pauseCampaign', 'click [data-action="complete-campaign"]': 'completeCampaign', 'click [data-action="archive-campaign"]': 'archiveCampaign',
        'input [data-campaign-search]': 'renderCampaigns', 'change [data-campaign-status]': 'renderCampaigns', 'change [name="channel"]': 'filterPurposeOptions',
        'submit [data-campaign-form]': 'saveCampaign',
    };

    setup() { this.setPageTitle('Campaigns'); this.workspace = null; this.currentCampaign = null; this.preview = null; }
    afterRender() { super.afterRender(); document.body.classList.add('nexa-campaigns-page'); this.once('remove', () => document.body.classList.remove('nexa-campaigns-page')); this.load(); }
    async load() { this.setState('loading'); try { this.workspace = await Espo.Ajax.getRequest('Nexa/campaigns/workspace'); this.populateOptions(); this.renderSummary(); this.renderCampaigns(); this.text('[data-sending-message]', this.workspace.sendingMessage || 'Activation does not send communication.'); this.setState('ready'); } catch (error) { this.setState('error'); Espo.Ui.error(error?.message || 'Campaigns could not be loaded.'); } }
    setState(state) { this.element.querySelectorAll('[data-campaign-state]').forEach(node => { node.hidden = node.dataset.campaignState !== state; node.style.display = node.hidden ? 'none' : ''; }); }
    populateOptions() {
        this.element.querySelector('[data-type-options]').innerHTML = (this.workspace.types || []).map(value => `<option value="${this.escape(value)}">${this.escape(value)}</option>`).join('');
        this.element.querySelector('[data-channel-options]').innerHTML = (this.workspace.channels || []).map(item => `<option value="${this.escape(item.id)}">${this.escape(item.name)}</option>`).join('');
        this.element.querySelector('[data-purpose-options]').innerHTML = '<option value="">Choose a consent purpose</option>' + (this.workspace.purposes || []).map(item => `<option value="${this.escape(item.id)}" data-channels="${this.escape((item.channels || []).join(','))}">${this.escape(item.name)}${item.policyVersion ? ` (${this.escape(item.policyVersion)})` : ''}</option>`).join('');
        const choices = (name, selected = []) => (this.workspace.segments || []).map(item => `<label><input type="checkbox" name="${name}" value="${this.escape(item.id)}" ${selected.includes(item.id) ? 'checked' : ''}><span><strong>${this.escape(item.name)}</strong><small>${Number(item.memberCount || 0)} members${item.type ? ` / ${this.escape(item.type)}` : ''}</small></span></label>`).join('') || '<p>Create a segment before configuring a campaign audience.</p>';
        this.renderSegmentChoices = choices;
        this.element.querySelector('[data-audience-options]').innerHTML = choices('audienceIds'); this.element.querySelector('[data-exclusion-options]').innerHTML = choices('exclusionIds');
    }
    renderSummary() { const items = this.workspace?.campaigns || []; const sum = key => items.reduce((total, item) => total + Number(item[key] || 0), 0); this.text('[data-summary-total]', items.length); this.text('[data-summary-active]', items.filter(item => item.workflowStatus === 'active').length); this.text('[data-summary-eligible]', sum('eligibleCount')); this.text('[data-summary-suppressed]', sum('suppressedCount')); }
    renderCampaigns() {
        if (!this.workspace) return; const query = (this.element.querySelector('[data-campaign-search]')?.value || '').trim().toLowerCase(); const status = this.element.querySelector('[data-campaign-status]')?.value || '';
        const items = (this.workspace.campaigns || []).filter(item => (!status || item.workflowStatus === status) && (!query || `${item.name} ${item.type} ${item.channel} ${item.purposeName || ''}`.toLowerCase().includes(query)));
        this.element.querySelector('[data-campaign-list]').innerHTML = items.map(item => { const canActivate = ['draft','paused'].includes(item.workflowStatus); const action = canActivate ? `<button class="btn btn-icon is-primary" data-action="activate-campaign" data-id="${this.escape(item.id)}" title="Check and activate audience"><span class="fas fa-play"></span></button>` : item.workflowStatus === 'active' ? `<button class="btn btn-icon" data-action="pause-campaign" data-id="${this.escape(item.id)}" title="Pause"><span class="fas fa-pause"></span></button>` : ''; return `<tr><td><div class="nexa-campaign-name"><span class="fas fa-bullhorn"></span><div><strong>${this.escape(item.name)}</strong><small>${this.escape(item.type || 'Campaign')} / version ${item.version}</small></div></div></td><td><span class="nexa-campaign-badge is-${this.escape(item.workflowStatus)}">${this.escape(this.label(item.workflowStatus))}</span></td><td>${this.escape(this.label(item.channel))}</td><td>${this.escape(item.purposeName || 'Not selected')}</td><td>${item.matchedCount}</td><td>${item.eligibleCount}</td><td>${item.suppressedCount}</td><td>${this.escape(this.dateTime(item.lastEvaluatedAt))}</td><td><div class="nexa-campaign-actions"><button class="btn btn-icon" data-action="edit-campaign" data-id="${this.escape(item.id)}" title="Edit"><span class="fas fa-pen"></span></button>${action}<a class="btn btn-icon" href="#Campaign/view/${encodeURIComponent(item.id)}" title="Open native campaign record"><span class="fas fa-external-link-alt"></span></a><button class="btn btn-icon is-danger" data-action="archive-campaign" data-id="${this.escape(item.id)}" title="Archive"><span class="fas fa-archive"></span></button></div></td></tr>`; }).join('');
        this.text('[data-campaign-count]', `${items.length} campaign${items.length === 1 ? '' : 's'}`); const empty = this.element.querySelector('[data-campaign-empty]'); empty.hidden = items.length > 0; empty.style.display = empty.hidden ? 'none' : ''; this.element.querySelector('.nexa-campaign-table-wrap').style.display = items.length ? '' : 'none';
    }
    newCampaign() { this.openEditor(null); }
    editCampaign(event) { this.openEditor((this.workspace.campaigns || []).find(item => item.id === event.currentTarget.dataset.id)); }
    openEditor(item) {
        this.currentCampaign = item || null; this.preview = null; const form = this.element.querySelector('[data-campaign-form]'); form.reset();
        form.elements.name.value = item?.name || ''; form.elements.type.value = item?.type || 'Email'; form.elements.channel.value = item?.channel || 'email'; form.elements.purposeId.value = item?.purposeId || ''; form.elements.enrollmentMode.value = item?.enrollmentMode || 'snapshot'; form.elements.startDate.value = item?.startDate || ''; form.elements.endDate.value = item?.endDate || ''; form.elements.description.value = item?.description || '';
        this.element.querySelector('[data-audience-options]').innerHTML = this.renderSegmentChoices('audienceIds', item?.audienceIds || []); this.element.querySelector('[data-exclusion-options]').innerHTML = this.renderSegmentChoices('exclusionIds', item?.exclusionIds || []); this.text('[data-editor-title]', item ? `Edit ${item.name}` : 'Create campaign'); this.text('[data-editor-status]', ''); this.text('[data-error="name"]', ''); this.resetPreview(); this.filterPurposeOptions();
        const editor = this.element.querySelector('[data-campaign-editor]'); editor.hidden = false; editor.style.display = 'grid'; document.body.classList.add('nexa-modal-open'); setTimeout(() => form.elements.name.focus(), 0);
    }
    closeEditor() { const editor = this.element.querySelector('[data-campaign-editor]'); editor.hidden = true; editor.style.display = 'none'; document.body.classList.remove('nexa-modal-open'); }
    filterPurposeOptions() { const form = this.element.querySelector('[data-campaign-form]'); const channel = form.elements.channel.value; [...form.elements.purposeId.options].forEach(option => { if (!option.value) return; const channels = (option.dataset.channels || '').split(',').filter(Boolean); option.hidden = channels.length > 0 && !channels.includes(channel); }); if (form.elements.purposeId.selectedOptions[0]?.hidden) form.elements.purposeId.value = ''; }
    payload() { const form = this.element.querySelector('[data-campaign-form]'); const checked = name => [...form.querySelectorAll(`input[name="${name}"]:checked`)].map(node => node.value); return {name: form.elements.name.value.trim(), type: form.elements.type.value, channel: form.elements.channel.value, purposeId: form.elements.purposeId.value, enrollmentMode: form.elements.enrollmentMode.value, startDate: form.elements.startDate.value || null, endDate: form.elements.endDate.value || null, description: form.elements.description.value.trim(), workflowStatus: this.currentCampaign?.workflowStatus || 'draft', audienceIds: checked('audienceIds'), exclusionIds: checked('exclusionIds')}; }
    validate(payload) { this.text('[data-error="name"]', ''); if (!payload.name) { this.text('[data-error="name"]', 'Enter a campaign name.'); return false; } if (!payload.audienceIds.length) { Espo.Ui.error('Choose at least one audience segment.'); return false; } if (!payload.purposeId) { Espo.Ui.error('Choose the consent purpose for this campaign.'); return false; } return true; }
    async previewCampaign() { const payload = this.payload(); if (!this.validate({...payload, name: payload.name || 'Preview'})) return; this.text('[data-editor-status]', 'Checking audience and consent...'); try { this.preview = await Espo.Ajax.postRequest('Nexa/campaigns/preview', payload); this.renderPreview(this.preview); this.text('[data-editor-status]', `Checked ${this.preview.matchedCount} matching contacts.`); } catch (error) { this.text('[data-editor-status]', ''); Espo.Ui.error(error?.message || 'The audience could not be checked.'); } }
    renderPreview(result) { this.text('[data-preview-matched]', result.matchedCount); this.text('[data-preview-eligible]', result.eligibleCount); this.text('[data-preview-suppressed]', result.suppressedCount); const labels = {not_marketing_contact:'Not a marketing contact',do_not_contact_all:'Do not contact enabled',do_not_contact_channel:'Channel blocked',audience_opt_out:'Opted out of this audience',missing_email:'No email address',consent_not_granted:'Consent not granted',consent_expired:'Consent expired'}; const entries = Object.entries(result.reasonCounts || {}); this.element.querySelector('[data-preview-reasons]').innerHTML = entries.length ? `<strong>Suppression reasons</strong>${entries.map(([key,count]) => `<span>${this.escape(labels[key] || this.label(key))}<b>${count}</b></span>`).join('')}` : '<p>No contacts are currently suppressed.</p>'; this.element.querySelector('[data-preview-people]').innerHTML = (result.sample || []).map(person => `<div class="${person.eligible ? 'is-eligible' : 'is-suppressed'}"><span class="fas ${person.eligible ? 'fa-check-circle' : 'fa-ban'}"></span><p><strong>${this.escape(person.name)}</strong><small>${this.escape(person.email || (person.reasons || []).map(key => labels[key] || this.label(key)).join(', '))}</small></p></div>`).join('') || '<p>No contacts match the selected segments.</p>'; }
    resetPreview() { ['matched','eligible','suppressed'].forEach(key => this.text(`[data-preview-${key}]`, 0)); this.element.querySelector('[data-preview-reasons]').innerHTML = '<p>Choose the audience, purpose and channel, then run the check.</p>'; this.element.querySelector('[data-preview-people]').innerHTML = ''; }
    async saveCampaign(event) { event.preventDefault(); const payload = this.payload(); if (!this.validate(payload)) return; Espo.Ui.notify('Saving campaign...'); try { if (this.currentCampaign) await Espo.Ajax.putRequest(`Nexa/campaigns/${encodeURIComponent(this.currentCampaign.id)}`, payload); else await Espo.Ajax.postRequest('Nexa/campaigns', payload); Espo.Ui.success('Campaign saved.'); this.closeEditor(); await this.load(); } catch (error) { Espo.Ui.notify(false); Espo.Ui.error(error?.message || 'The campaign could not be saved.'); } }
    activateCampaign(event) { const item = (this.workspace.campaigns || []).find(row => row.id === event.currentTarget.dataset.id); if (!item) return; this.confirm({message:`Activate ${item.name}? Consent and contact preferences will be checked now. Eligible contacts will be enrolled, but no messages will be sent.`,confirmText:'Activate audience'}, async () => { Espo.Ui.notify('Checking and activating audience...'); try { const result = await Espo.Ajax.postRequest(`Nexa/campaigns/${encodeURIComponent(item.id)}/enroll`); Espo.Ui.success(`${result.eligibleCount} eligible contacts enrolled; ${result.suppressedCount} suppressed.`); await this.load(); } catch (error) { Espo.Ui.notify(false); Espo.Ui.error(error?.message || 'The campaign audience could not be activated.'); } }); }
    pauseCampaign(event) { this.changeStatus(event.currentTarget.dataset.id, 'paused', 'Campaign paused.'); }
    completeCampaign(event) { this.changeStatus(event.currentTarget.dataset.id, 'completed', 'Campaign completed.'); }
    archiveCampaign(event) { const item = (this.workspace.campaigns || []).find(row => row.id === event.currentTarget.dataset.id); if (!item) return; this.confirm({message:`Archive ${item.name}? Versions and enrollment history will be retained.`,confirmText:'Archive campaign'}, () => this.changeStatus(item.id, 'archived', 'Campaign archived.')); }
    async changeStatus(id, status, message) { Espo.Ui.notify('Updating campaign...'); try { await Espo.Ajax.postRequest(`Nexa/campaigns/${encodeURIComponent(id)}/status`, {status}); Espo.Ui.success(message); await this.load(); } catch (error) { Espo.Ui.notify(false); Espo.Ui.error(error?.message || 'The campaign status could not be updated.'); } }
    dateTime(value) { if (!value) return 'Not checked'; const parsed = new Date(String(value).replace(' ', 'T') + (String(value).includes('Z') ? '' : 'Z')); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleString(); }
    label(value) { return String(value || '').replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase()); }
    text(selector, value) { const node = this.element.querySelector(selector); if (node) node.textContent = String(value); }
    escape(value) { const node = document.createElement('div'); node.textContent = String(value ?? ''); return node.innerHTML; }
});
