<main class="nexa-campaign-workspace">
    <header class="nexa-campaign-heading">
        <div><p>Marketing</p><h1>Campaigns</h1><span>Plan campaigns, verify consent and activate governed audiences.</span></div>
        <button class="btn btn-primary" type="button" data-action="new-campaign"><span class="fas fa-plus" aria-hidden="true"></span>Create campaign</button>
    </header>
    <section class="nexa-campaign-state" data-campaign-state="loading"><span class="fas fa-circle-notch fa-spin"></span><strong>Loading campaigns</strong></section>
    <section class="nexa-campaign-state" data-campaign-state="error" hidden><span class="fas fa-exclamation-circle"></span><strong>Campaigns could not be loaded.</strong><button class="btn btn-default" data-action="reload">Try again</button></section>
    <div data-campaign-state="ready" hidden>
        <section class="nexa-campaign-summary" aria-label="Campaign summary"><div><span>Total campaigns</span><strong data-summary-total>0</strong></div><div><span>Active</span><strong data-summary-active>0</strong></div><div><span>Eligible contacts</span><strong data-summary-eligible>0</strong></div><div><span>Suppressed</span><strong data-summary-suppressed>0</strong></div></section>
        <section class="nexa-campaign-boundary"><span class="fas fa-shield-alt"></span><div><strong>Consent is checked before activation</strong><p data-sending-message>Campaign activation enrolls contacts but does not send communication.</p></div></section>
        <div class="nexa-campaign-toolbar"><label><span class="fas fa-search"></span><input class="form-control" type="search" data-campaign-search placeholder="Search campaigns" aria-label="Search campaigns"></label><select class="form-control" data-campaign-status aria-label="Filter campaign status"><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select><strong data-campaign-count>0 campaigns</strong></div>
        <div class="nexa-campaign-table-wrap" role="region" aria-label="Campaigns" tabindex="0"><table class="table"><thead><tr><th>Campaign</th><th>Status</th><th>Channel</th><th>Purpose</th><th>Audience</th><th>Eligible</th><th>Suppressed</th><th>Last checked</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody data-campaign-list></tbody></table></div>
        <section class="nexa-campaign-empty" data-campaign-empty hidden><span class="fas fa-bullhorn"></span><h2>Create your first campaign</h2><p>Choose reusable segments and verify every contact against consent before activation.</p><button class="btn btn-primary" data-action="new-campaign">Create campaign</button></section>
    </div>
    <div class="nexa-campaign-editor" data-campaign-editor hidden>
        <div class="nexa-campaign-dialog" role="dialog" aria-modal="true" aria-labelledby="nexa-campaign-title">
            <header><div><p>Campaign setup</p><h2 id="nexa-campaign-title" data-editor-title>Create campaign</h2></div><button class="btn btn-icon" type="button" data-action="close-editor" title="Close"><span class="fas fa-times"></span></button></header>
            <form data-campaign-form novalidate>
                <div class="nexa-campaign-form-grid">
                    <section><h3>Campaign details</h3><label><span>Name <b>*</b></span><input class="form-control" name="name" maxlength="255" required placeholder="Example: Autumn customer offer"><em data-error="name"></em></label><div class="nexa-campaign-pair"><label><span>Type</span><select class="form-control" name="type" data-type-options></select></label><label><span>Channel</span><select class="form-control" name="channel" data-channel-options></select></label></div><div class="nexa-campaign-pair"><label><span>Start date</span><input class="form-control" type="date" name="startDate"></label><label><span>End date</span><input class="form-control" type="date" name="endDate"></label></div><label><span>Description</span><textarea class="form-control" name="description" rows="4" maxlength="2000" placeholder="Summarize the campaign objective and offer."></textarea></label></section>
                    <section><h3>Audience and permission</h3><label><span>Consent purpose <b>*</b></span><select class="form-control" name="purposeId" data-purpose-options></select><small>The legal purpose checked for every selected contact.</small></label><fieldset><legend>Include segments <b>*</b></legend><div class="nexa-campaign-segment-list" data-audience-options></div></fieldset><fieldset><legend>Exclude segments</legend><div class="nexa-campaign-segment-list" data-exclusion-options></div></fieldset><label><span>Enrollment</span><select class="form-control" name="enrollmentMode"><option value="snapshot">Fixed snapshot when activated</option><option value="continuous">Continuously evaluated audience</option></select></label></section>
                </div>
                <section class="nexa-campaign-preview"><header><div><h3>Audience check</h3><p>See who is eligible and why anyone is suppressed.</p></div><button class="btn btn-default" type="button" data-action="preview-campaign"><span class="fas fa-user-check"></span>Check audience</button></header><div class="nexa-campaign-preview-counts"><div><strong data-preview-matched>0</strong><span>Matched</span></div><div><strong data-preview-eligible>0</strong><span>Eligible</span></div><div><strong data-preview-suppressed>0</strong><span>Suppressed</span></div></div><div class="nexa-campaign-preview-body"><div data-preview-reasons><p>Choose the audience, purpose and channel, then run the check.</p></div><div data-preview-people></div></div></section>
                <footer><span data-editor-status></span><button class="btn btn-default" type="button" data-action="close-editor">Cancel</button><button class="btn btn-primary" type="submit"><span class="fas fa-save"></span>Save campaign</button></footer>
            </form>
        </div>
    </div>
</main>
